FROM docker.io/alpine:latest

# Install packages
RUN apk add --update-cache \
    rsync \
    openssh-client \
    tzdata \
    && rm -rf /var/cache/apk/*

# Create group and users and add users to group
RUN addgroup -g 2000 home \
    && adduser -D -u 1000 -G home coen \
    && adduser -D -u 1001 -G home anne

USER coen
